apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbgen
  name: dbgen

spec:
  selector:
    matchLabels:
      app: dbgen
  template:
    metadata:
      labels:
        app: dbgen
    spec:
      containers:
      - name: dbgen
        image: dbgen:0.0.3
        args: ["-i", "template.sql", "-N", "50000000", "-R", "2000000", "-r", "1000", "--s3", "--s3-bucket", "test", "--s3-access-key", "minioadmin", "--s3-secret-key", "minioadmin"]
        ports:
        - containerPort: 9000
