#!/usr/bin/env python3
"""
Export all routines (procedures and functions) from MySQL sys schema.
Removes COMMENT clauses from the CREATE statements.
"""

import mysql.connector
import re
import sys
import argparse


def connect_to_mysql(host, port, user, password, database='sys'):
    """Connect to MySQL database."""
    try:
        conn = mysql.connector.connect(
            host=host,
            port=port,
            user=user,
            password=password,
            database=database
        )
        return conn
    except mysql.connector.Error as err:
        print(f"Error connecting to MySQL: {err}")
        sys.exit(1)


def get_routines(cursor):
    """Get all routines from sys schema."""
    query = """
        SELECT routine_name, routine_type 
        FROM information_schema.routines 
        WHERE routine_schema = 'sys'
        ORDER BY routine_type, routine_name
    """
    cursor.execute(query)
    return cursor.fetchall()


def get_routine_definition(cursor, routine_name, routine_type):
    """Get CREATE statement for a routine."""
    if routine_type == 'FUNCTION':
        query = f"SHOW CREATE FUNCTION `sys`.`{routine_name}`"
    else:  # PROCEDURE
        query = f"SHOW CREATE PROCEDURE `sys`.`{routine_name}`"
    
    try:
        cursor.execute(query)
        result = cursor.fetchone()
        if result:
            # Result format: (name, sql_mode, create_statement, charset, collation, db_collation)
            # The CREATE statement is typically in the 3rd column (index 2)
            return result[2] if len(result) > 2 else result[1]
        return None
    except mysql.connector.Error as err:
        print(f"Error getting definition for {routine_type} {routine_name}: {err}")
        return None


def remove_comments(create_statement):
    """Remove COMMENT 'xxx' clauses from CREATE statement."""
    # Pattern to match COMMENT 'xxx' or COMMENT "xxx"
    # The comment can span multiple lines and contain escaped characters
    # Use DOTALL so . matches newlines within the regex itself
    # Match COMMENT followed by optional whitespace, then a quoted string
    # The quoted string can contain: any non-quote/backslash OR escape sequences
    pattern = r"\s*COMMENT\s+'(?:[^'\\]|\\.|'')*'|\s*COMMENT\s+\"(?:[^\"\\]|\\.)*\""
    cleaned = re.sub(pattern, '', create_statement, flags=re.IGNORECASE | re.DOTALL)
    return cleaned


def replace_keywords_with_comments(create_statement, keywords):
    """Replace occurrences of specific keywords with comments in the CREATE statement."""
    for keyword in keywords:
        # Pattern to match the keyword as a whole word (not part of another word)
        pattern = rf"\b{re.escape(keyword)}\b"
        # Replace the keyword with a comment
        create_statement = re.sub(pattern, f"/* {keyword} */", create_statement, flags=re.IGNORECASE)
    return create_statement


def export_routines(host='127.0.0.1', port=3306, user='root', password='', output_file='sys_routines.sql'):
    """Export all sys routines to a file."""
    conn = connect_to_mysql(host, port, user, password)
    cursor = conn.cursor()
    
    routines = get_routines(cursor)
    print(f"Found {len(routines)} routines in sys schema")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        # Write header
        f.write("-- MySQL sys schema routines export\n")
        f.write("-- Generated by export_sys_routines.py\n")
        f.write("--\n\n")
        f.write("USE sys;\n\n")
        
        for routine_name, routine_type in routines:
            # Skip routines with prefix 'ps_'
            if routine_name.startswith('ps_'):
                print(f"Skipping {routine_type}: {routine_name} (prefix 'ps_')")
                continue
            # Skip specific routine names
            if routine_name in {"diagnostics", "statement_performance_analyzer", "sys_get_config", "execute_prepared_stmt", "create_synonym_db"}:
                print(f"Skipping {routine_type}: {routine_name} (excluded by name)")
                continue
            print(f"Exporting {routine_type}: {routine_name}")
            
            # Get the CREATE statement
            create_stmt = get_routine_definition(cursor, routine_name, routine_type)
            
            if create_stmt:
                # Remove COMMENT clauses
                without_cmt_stmt = remove_comments(create_stmt)
                cleaned_stmt = replace_keywords_with_comments(without_cmt_stmt, ["NO SQL", "MODIFIES SQL DATA", "READS SQL DATA", "DETERMINISTIC"])
                
                # Write to file
                f.write(f"-- {routine_type}: {routine_name}\n")
                f.write("DELIMITER ;;\n")
                f.write(cleaned_stmt)
                f.write(";;\n")
                f.write("DELIMITER ;\n\n")
            else:
                f.write(f"-- WARNING: Could not export {routine_type} {routine_name}\n\n")
    
    cursor.close()
    conn.close()
    
    print(f"\nExport completed. Output written to: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Export MySQL sys schema routines to a file'
    )
    parser.add_argument('--host', default='127.0.0.1',
                        help='MySQL host (default: 127.0.0.1)')
    parser.add_argument('--port', type=int, default=3306,
                        help='MySQL port (default: 3306)')
    parser.add_argument('--user', default='root',
                        help='MySQL user (default: root)')
    parser.add_argument('--password', default='',
                        help='MySQL password (default: empty)')
    parser.add_argument('--output', default='sys_routines.sql',
                        help='Output file (default: sys_routines.sql)')
    
    args = parser.parse_args()
    
    export_routines(
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password,
        output_file=args.output
    )


if __name__ == '__main__':
    main()
